jobs:
- job: BuildManylinuxWithSudo
  pool:
    vmImage: 'ubuntu-22.04'
  steps:
  - checkout: none
  - task: Bash@3
    displayName: 'Generate Dockerfile'
    inputs:
      targetType: inline
      script: |
        echo "FROM quay.io/pypa/manylinux_2_28_x86_64" > $(Pipeline.Workspace)/Dockerfile
        echo "RUN dnf -y install sudo && dnf clean all" >> $(Pipeline.Workspace)/Dockerfile
  - task: Bash@3
    displayName: 'Print Dockerfile'
    inputs:
      targetType: inline
      script: cat $(Pipeline.Workspace)/Dockerfile
  - task: Docker@2
    displayName: 'Build and push Docker image'
    inputs:
      containerRegistry: 'ContainerService3'
      repository: '$(Build.DefinitionName)'
      Dockerfile: '$(Pipeline.Workspace)/Dockerfile'
      buildContext: '$(Pipeline.Workspace)'
      tags: |
        latest
