variables:
- group: common
- template: /.azuredevops/variables-global.yml

parameters:
- name: CLI11Version
  type: string
  default: "main"

resources:
  repositories:
  - repository: pipelines_repo
    type: github
    endpoint: ROCm
    name: ROCm/ROCm

trigger: none
pr: none

jobs:
  - template: ${{ variables.CI_DEPENDENCIES_PATH }}/CLI11.yml
    parameters:
      CLI11Version: ${{ parameters.CLI11Version }}
